host: 'craigmills'
oauth_key: 'LvsRbBtV2iVkH0u3qSzNBXOT3BmC810l7oDxK99c'
oauth_secret: 'EOEY6BWfYIyM9yfKBJ1C58Z1ZgFZTA7vtbUlaeXP'
oauth_access_token: '1LABjrbPCQL9HYpQcQJ3yZRH6sdaYhXxaAnj4X4r'
oauth_access_token_secret: 'WTgmox0YwyoKxdmgmKcg10SlADVhbqkkgxmokf2L'